CREATE TABLE IF NOT EXISTS posts (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  text LONGTEXT NOT NULL,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS photo_posts (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    image VARCHAR(255) NOT NULL,
    post_id BIGINT(20) UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (post_id) REFERENCES posts(id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    text LONGTEXT NOT NULL,
    post_id BIGINT(20) UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (post_id) REFERENCES posts(id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
